# Generated by Django 4.2.6 on 2023-10-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoapp',
            old_name='content',
            new_name='task_description',
        ),
    ]
